from __future__ import annotations

from typing import Protocol

from src.market.models import MarketQuote
from src.trading.models import Fill, Order, Trade


class Broker(Protocol):
    def submit_order(self, order: Order, quote: MarketQuote, at) -> tuple[Fill | None, Trade | None]: ...
    def cancel_order(self, order_id: str) -> bool: ...
    def query_orders(self) -> list[Order]: ...
    def query_trades(self) -> list[Trade]: ...
    def query_positions(self) -> dict: ...
    def query_cash(self) -> float: ...
